chore: add vitest failure

diff --git a/.github/workflows/vitest.yml b/.github/workflows/vitest.yml
--- a/.github/workflows/vitest.yml
+++ b/.github/workflows/vitest.yml
@@ -36,3 +36,10 @@ jobs:
           name: html-coverage-report
           path: coverage/index.html
 
+      - name: Fail if Vitest Failed
+        if: success() || failure()
+        run: |
+          if [ -f vitest_failed ]; then
+            echo "Vitest tests failed, marking job as failed."
+            exit 1
+          fi
